// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJMcWYYGb4ucSbnChKlNbF89SHzkYwJCM',
    appId: '1:262042761376:android:7aa6f248554043bca6b1c5',
    messagingSenderId: '262042761376',
    projectId: 'flutter-chat-app-47a12',
    storageBucket: 'flutter-chat-app-47a12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK-NNfOJp75hOexvSH7B3GZDbYBpXl6C8',
    appId: '1:262042761376:ios:2ec80300e982ac23a6b1c5',
    messagingSenderId: '262042761376',
    projectId: 'flutter-chat-app-47a12',
    storageBucket: 'flutter-chat-app-47a12.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK-NNfOJp75hOexvSH7B3GZDbYBpXl6C8',
    appId: '1:262042761376:ios:2ec80300e982ac23a6b1c5',
    messagingSenderId: '262042761376',
    projectId: 'flutter-chat-app-47a12',
    storageBucket: 'flutter-chat-app-47a12.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

}