// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyCshTe-6b6FFHtgo1n-nRTmwV9s4AN1M',
    appId: '1:795612661932:web:f483007e27869e5807b709',
    messagingSenderId: '795612661932',
    projectId: 'bookly-a3330',
    authDomain: 'bookly-a3330.firebaseapp.com',
    storageBucket: 'bookly-a3330.firebasestorage.app',
    measurementId: 'G-HZZMQQD78E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLQqFaW8y4OX04fmmrtCIaqEjgixRKko0',
    appId: '1:795612661932:android:aa7fd7be6496ecb507b709',
    messagingSenderId: '795612661932',
    projectId: 'bookly-a3330',
    storageBucket: 'bookly-a3330.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC87D4xRuDz-7ZNsZjiKxi0EEIU0Jhcrz0',
    appId: '1:795612661932:ios:f1f4580c70c3d32007b709',
    messagingSenderId: '795612661932',
    projectId: 'bookly-a3330',
    storageBucket: 'bookly-a3330.firebasestorage.app',
    iosBundleId: 'com.example.bookly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC87D4xRuDz-7ZNsZjiKxi0EEIU0Jhcrz0',
    appId: '1:795612661932:ios:f1f4580c70c3d32007b709',
    messagingSenderId: '795612661932',
    projectId: 'bookly-a3330',
    storageBucket: 'bookly-a3330.firebasestorage.app',
    iosBundleId: 'com.example.bookly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyCshTe-6b6FFHtgo1n-nRTmwV9s4AN1M',
    appId: '1:795612661932:web:e45d2f58de4c681d07b709',
    messagingSenderId: '795612661932',
    projectId: 'bookly-a3330',
    authDomain: 'bookly-a3330.firebaseapp.com',
    storageBucket: 'bookly-a3330.firebasestorage.app',
    measurementId: 'G-HEQN67MB0W',
  );

}